name: Build Nexo APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restaurar projeto Nexo
        env:
          NEXO_B64: >-
          UEsDBAoAAAAAAF0/N10AAAAAAAAAAAAAAAAfABwATmV4by1BdGVuZGUtMC4xLjMtcmVjb25zdHJ1aWRvL1VUCQADwYazasGGs2p1eAsAAQQAAAAABOkDAABQ
          SwMEFAAAAAgAXT83XbKiX19GAAAASQAAACsAHABOZXhvLUF0ZW5kZS0wLjEuMy1yZWNvbnN0cnVpZG8vYnVpbGQuZ3JhZGxlVVQJAAPBhrNqwYazanV4CwAB
          BAAAAAAE6QMAACvIKU3PzCtWqOZSAILMFAX15PxcvcS8lKL8zBS9xIKCnMzkxJLM/Dx1hbLUomIgQ0HdQs9cz1hdASRZqZCWmFOcylXLBQBQSwMEFAAAAAgA
          XT83XexHc7ILAwAAVAUAACgAHABOZXhvLUF0ZW5kZS0wLjEuMy1yZWNvbnN0cnVpZG8vUkVBRE1FLm1kVVQJAAPBhrNqwYazanV4CwABBAAAAAAE6QMAAG1U
          wW4UORC9z1eUlEtWCj0ksHBOApEm2UC0A+LaFXdNx7vdtrHdw7AnPoIPWIkDAiknxGWv/Sf7JbxyD2SQuGSidvnVq/deeY+eycbTcRbXCN2vDqsH9P+79xTF
          eJdyHMaP4wdPTIFjtpEa1F5dlMKj2expykIh+r8ke1p5u3PtFpVDYocf43uPk5XE8bMzlmkHA7eiE2NRpkiSJK6Zak5JcppbkNpUN7nvamqY1hKTsvHRttZx
          V81me3t05o3X00J+do/qZz7blTWcrXd/WFB0EpfAtUZqkk3oxltjszaMco0WxH4iLiZzrABxZrscUbAx3ZDs2uv0YIVBqjc3nBOHUL15eF1r7SmHPOAU8uXx
          Ng+dn2fZ5ELJbZkUEXeAUdvGIfgD6sCv3EX7zNmngiOq6863wJCy8UkhToZkyo0JVdWl+k/pfZaFC0PGiCRubUFaOv5e1eiwKfjS7RfEltDTluaN5daNX1K2
          RiFiAkPYk2i/7jjlpW2hfP0bunS+TfhjcFEhrsBW6JzXvDTRhqzMAkOTtXSFJZNFRVyxmZJ2NPl3ijLbcZwdX0NGTZqSdAiJa6K3DS3z0GCc/fMnF3T4WDuv
          QJxp+daZ+clgu0bzVNFz4v7airJoRDGgn0YGYJNQLo+f+jvYJxdzhnlHcw5/J4wl8YCCj5kd3FPPjVcbXI7SDtD79WBp/KQnU+LvrcrEP2X+YOo19CXiiDF0
          bfw06Itiq4lICbSdHVa0wD3uZLsQrcRSe1RRkeIUidwoGnoPGaH/B/8YScnT+G/a9fCrwIEHFV2CurgbqBjEcVIa2wzdxWoLVTo9RKds10oAFviMT79Xagg+
          vNKgH4eggbMOXXVVWR+AEG0vFjEOHTtMrGkTqr2ttYsfNOFu/K+XCLxHiudWdpqn2JFIG+7mDPocl3C0cZtX+PBzSAEdyhvV6EsTe53p9SC/JFoEnVyeXy5e
          LnTpoVGvoWKssnQ3XuMyrckaL1J9BWzr2oXqhxWCzPpCYIPuYliMbfEQuB+p4GnHLiXz/DuNavYNUEsDBBQAAAAIAF0/N12pyWtepwAAAA8BAAAuABwATmV4
          by1BdGVuZGUtMC4xLjMtcmVjb25zdHJ1aWRvL3NldHRpbmdzLmdyYWRsZVVUCQADwYazasGGs2p1eAsAAQQAAAAABOkDAACNjrEKwjAYhPc+RbbWxQdQHEqp
          oNg2VPcSmiNE0vwhSUWRvrttR0FwvI/j7nNmVNpWwgqFATayN/NwFHQkrxHmqIiUQbbZs0E8YIu55IVZsvJCGvB1gZOPC2UTmxIJByth+1eLQGaMmn5fVCSx
          DYhZ+w2P+enSNXXH2+ZcFreuLXlznX//FFxVPFHknu7o49aKAezA0hpPyuNimCba9maUYOlOOJcmH1BLAwQKAAAAAABdPzddAAAAAAAAAAAAAAAAIwAcAE5l
          eG8tQXRlbmRlLTAuMS4zLXJlY29uc3RydWlkby9hcHAvVVQJAAPBhrNqwYazanV4CwABBAAAAAAE6QMAAFBLAwQUAAAACABdPzddZJqffJwAAAALAQAALwAc
          AE5leG8tQXRlbmRlLTAuMS4zLXJlY29uc3RydWlkby9hcHAvYnVpbGQuZ3JhZGxlVVQJAAPBhrNqwYazanV4CwABBAAAAAAE6QMAAHWOwQrCMAxA7/2K3Hor
          06E/sJMXL35BXLIR7NrSdSKM/bvtHDIE3/GRvCTYqRc3wgxCoFs/GHQUvZDBEKy0mMQ7DYtSm4dZQcbhwGPAlkHfoyl7jl/eYGJHrNeRLINYvtED6tNqiDuc
          bGq866TfQoXdqQv9DxYGcSV4PH9Nwthz2l0pPDmOudZ4YjhU9a+/5u9BV+Zg6k96UYt6A1BLAwQKAAAAAABdPzddAAAAAAAAAAAAAAAAJwAcAE5leG8tQXRl
          bmRlLTAuMS4zLXJlY29uc3RydWlkby9hcHAvc3JjL1VUCQADwYazasGGs2p1eAsAAQQAAAAABOkDAABQSwMECgAAAAAAXT83XQAAAAAAAAAAAAAAACwAHABO
          ZXhvLUF0ZW5kZS0wLjEuMy1yZWNvbnN0cnVpZG8vYXBwL3NyYy9tYWluL1VUCQADwYazasGGs2p1eAsAAQQAAAAABOkDAABQSwMECgAAAAAAXT83XQAAAAAA
          AAAAAAAAADMAHABOZXhvLUF0ZW5kZS0wLjEuMy1yZWNvbnN0cnVpZG8vYXBwL3NyYy9tYWluL2Fzc2V0cy9VVAkAA8GGs2rBhrNqdXgLAAEEAAAAAATpAwAA
          UEsDBBQAAAAIAF0/N12DX/YP5kIAAN/SAAA9ABwATmV4by1BdGVuZGUtMC4xLjMtcmVjb25zdHJ1aWRvL2FwcC9zcmMvbWFpbi9hc3NldHMvaW5kZXguaHRt
          bFVUCQADwYazasGGs2p1eAsAAQQAAAAABOkDAACsPNt240Zy7/oKLOfYlHYJCHfwIimxHefY58x4c3aSOcnM8UMTaBJYgQANgJRkLr8mD3nKY77AP5aqvgCN
          C0nJu9lYBBrdXdV1r+ruuftDlIfVy5ZqcbVJH67u8EdLSba+H20r/du/jB7uYkqih7sNrYgWxqQoaXU/2lUrfToSrRnZ0PvRPqFP27yoRlqYZxXNoNdTElXx
          fUT3SUh19jJJsqRKSKqXIUnpvTWRo/RVUt2H+Z4Wcta4qrY6/WWX7O9H3/EZ9Y803BVJ9aL/W54m4YsCKqIrsksrvSxCbZzlGR0vtDIskq1o2mUlWVE9ydKE
          f6teUjr8Kdms2YeIVGS+0FYAojUtwMxo2G5bkpLqgFrdsMqLjU7CKskz0damVhXTDdXDPM0LZRXvzKVlWst2V9YJCIYjlL5pso4rQLJ4hO5VUqX04Sf6nGvf
          wOeI3t3ypqs7ttKHq3mR59VB15fruYCy0PUtyWg6f2e51tKeyXcbGkLbczxoQJLM39m+Y7sBvCbZ4/zdylw5KwJvm11Fo/m72ZQEywjeSRgCZvN3S7qyfbdu
          YIMsYs/MENrKfFXNi/WSXFszc2K79sQyzYlhzm4Q/q7YpgBw6ZJghVM+kSIDiHboB4hOBIJJC2hYEZcghIJEya6c2/b2eaHSaY50OV798bDMn/Uy+TXJ1vNl
          XkS00KHluMyjl8OGFOskm5uLJQkf10W+y6L5nhTXSKMbPpt4hxXcLFAO5pa3fb61DE/TyXaLAvRSVnQz+Rbo9PiBhB/Z679Cz8n4I13nVPuPH8eTv+TLvMon
          JclKvaRFslroT3T5mFR6RbZ6DHxkvOTSMK8K6LclBVDuuNxVVZ6B0mx31aSizxU0k0lJU5C/A0MoyWKYUfY8gHqUMMc2T0BKCtE6j5KSLFMaHfItCUF95obr
          LURXoTgSFDkB7G0Yz1d5uCv1fVImAJdP2WmTADrNHFy78ZDvKiaIwGWtBM2PNM4XLl83C/Fdz1crsE5zZ/ss6cF53uYxaqNgr6ReuV8fmH3ikhRTXB1/Lqsi
          f6RzoBau7zscJtq4RZtbRrBYJWnK5xWfEJ2QbOcMotr4V+CMaF2lFGQzLlA/zKNRxjRNQSifxbzB1ATwUkg1sqvyxSbJdIEcaM0+PhpVvj2IlmAK/bckilDY
          EXeN/bF8aAYJ2KbkZY4wFwSYl+kJSGo5RwLSYvHXXVklqxddWJc5sBNM9pJWT5RmR2MJHI4OlyZZw4ItC6CltIJ3HSdBXHQDMeN2NPkV2OjJ1yeO+dQ0BQyt
          3BCgQtPXMvvz1cou1JPZoZt6jcs0Dx8XTCAkrQynBc9HeEDZR8F012yYzp6FqRDWxXKwqWskpPCpmNQGr8FmXSTRAp6AnC1iqfjMTFMlTwDya5A9uJ9CIOjM
          GgTZs5Brq6MQuOibDvae+dVFZHqLY46gvTZum28URBld1HUEnK5JdpBiaDViiJw8GvSFLov86RKHDas7tWcO8RytiM7sDzrc+W67pUUIvrjRG1NDcsaWAtFh
          EFvyYXk9obUYDso8DNEOTsfYVpcyHRJ+twfN6aHnqLN4bbheb7x73B5UxFykLKPIoU8jsCxdnbJ7M3oemJIke+nxpd0LxJJJ+KEv9AAHbGl+2OZlglHPvKAp
          qZI9XWBQt0rzp3mcRBHNVGHD6Umhr1FUYY5ryzYjup4oMmjfqG83N2+RfP6Fv9w0ltGtyauD9WSWkuM+Jyvg3EHawPF4US+GLAEYkHMhPKtO99Cl5Da/YOTR
          HeDkAmfUXVQM4R1cr1Fd/tJbAYQz+H9mNKC5LH6JSQTkQ1abmg1sqUc4E97oqo02X43WEk3bP2WXhSCh1MFMvEX6INsxJXG0reKbHNdsWXRmCYZED1X9VW6D
          MUH4m8MFb/RUkO2BeU98muOfo7EFF1yD4rG8fg6if8mKSnlBusx6PoHZkAGD1NGfjnXscsDAUIWhbqwLXPmAXknA/BMPcjfJ83WSaSXE0ZNWZ7C1X02UeOym
          b9oxAL8RQLlNPwyZeWWcCMfN8GhEkENwEfAbsfZ71GGS20ygBk/A5Sp7LaO6gqDwD1mihENuoAQ/zOtYwT/GkZ/zd+CUOpbdY+vTmoCS+QT5fcqkvMqMksKS
          IEd5OQy7XnsgATknrXzWdZyX1aEb6p6V8iGlxal4pqXOJZIuq+2Heb8B5ER3QRBjtQP1FBQxza94Y5hvQBGqg8JHR+XjFNloty2NLUg4x+R6Tw+N82clhWtj
          NvVgDQnQFwVN2CuFCez5YkDUlhtrSG4Eo2pYZ5leVqQqDy2w+EcHoNBSsVLAbpOV4Da3lFTXzsRaAVlrSW8ZaTTmfMom0PJYjPW20JCryHDsx+fXjGy3Ud3I
          dMiotVTAHnQzcrqULGk6EKV0DafioD02mrJaCtai2g7lrK8YsimClEhDjJ3szuxtt8mSJxlqHQ1M87uB1JDJllwJEMbRCEkRNZyanSb6m5jXyIW+zCHb3Qjl
          WIE8qYqrpufABbptE5C5X7RsA7SqcXZxIYu6gsKhDRsihDBfJUVZ6WGcpPXCGS9N8T0lvc9iVglFdkX5u6StQsktRcnfqgmX3TmzQ52UneMHXjGjfUPOHO2g
          eLQ8eo89MKNqShRHawm9p1sNbOf2hQVBc0s0bVXJtIbXI4Wfyb5YgQbZR10La3u7o5HlFT28hZCe6oddWX+4TNq+TJpdu8exUWkTKLQJOmBkIKOG+nJFWpM/
          8QYDC42HFl9E1dFp1Y5Eo+krwxhCKmRsBEWoIGnoq5r7e7VfiUe7NG8ymjlLD0wOXBNFMC4lDVewi9/zqq/TiNbMBq/WQdr5+iimVy9YJRSsgGS0z9FnjS0r
          orBRfte4M2nXfc5Y55YOSHsTdBya79XT80qoeKkLouJd1EWbkKYTfTpvNED2kFycLESLFbqdIJjZhza+h4KyvpCEVwlESGr/2WCKryx+PmfWNs5TQLVLidZH
          oQDvfDOwpoGcBDLH9PVmiTGXmziypx8hXtiV3YLEkDllRSDmveYsFW+VSYN2MMGmr55ymOc10RgEYRr8p+So5VNShXEvrz0fhrDh/gUfa3PRrwFo7aqQ04L+
          FmvvSGtf5es1pHtkCyEmeJ2Q8gRB1va77aI46gghU15lgXywnHFayG3zlJD3q0adnQyB+3xJIdanao3mhCvol26Q/Q6rgqzYHsH5nLVdZkQfzaer8w3NsLyy
          xiuMafg4ZAgHfX6ncNaeQ67xxFTMBjRZD3tCmf3Pa1w3zBaRl7dkGkGTabBIG4ZfcPiDDFSdi/n26MoSoI38FUWQzqcTFY5iB7Je4xW80R6fSY3qqET4WgRk
          5KtVs72G5VRs1QwgcvpyLmVoqyo3AounGEwES6DofFtQVudiZTlZcUHF69RVj8YjfXmCRXSCjnahTPJZtYkzpL0YfM7eni4NWWYtAGhs+pUXZnaRIivchf67
          dqPkzIj52UiJ9+C7Dptt9XJQ/ETH9uKWCw9UXxGaRaSM6aXMTMDU+A9WCESo4CkbjN5A2HVa7uzLm0qt3UKtV5UVDJS4tf2L2yC9fZXA1sVgW4nUsWTDgTOW
          8yCr2RRYJc8Uy9wi1WOmGA3voD3T4YsKiO+IKhHXrxAQRRDb2ubi9fbO4/auZbACWWgatG2XBE4uU8bbffWLkoJXGOYcmVNF6XpjlJF+Nkz5VnFBjXU8uyG5
          wEVJlmwlPbatXk9D1NMGHdRQzwFXPOxzTcEytvEiEThXiO0EDadQ1cAsZIdePlHlpKxOSNzMkv7/vNBpdcN/XWPuqYgL2jervUsCUXV4jQKp6ZrjY2/ejj0E
          dfqLZW5cJbYiaWpe19FEKfK+uZDexhzclFJCFsOalu2NJEynMXjT3pmm6QmaGWUMUe3riGLe1OCx/ADz0i7JkwzPYrSzZ9M2fXO5XNbLcM3F2TBa6IaqLkyh
          aBa1zDzfp9rkEVGrzAqPfHGaonahM3sfNy6Una74BxTl7JqyEHA37sWTu+COXeOpGeuCLOXhDbe2bKw+3Z51sGbAwQuzqzMzxgyv3ZCiswXo1B/QC0PONlxz
          6fKgJnhv01Sso5NwqtmXxULKMCatIr896zDDnfaYUSscVgRcaZ9lmDTlkddyt1yqQR7LvAcKJIHYD+J/TpdgbNXdzECAOps/7VzZ94YDNbkQHnWR7OUppgXt
          1B24e2T4G5uT1cOe6F3c/zO7+38nKOHKLTKBFrOKjPLdggPnHx5IPFz0Ta2Mk4cAuMmTlyelTfLujadazgVrDUxexZAFsCaJ7Z8Hqw+K9cotEsFOxQyFSJ5L
          MxWIIgZQEma7Vm1Xif3csy7wxF7kQM3oQkgIxnm3XtMSDfPlxCBQVMwR5YhmuFzbue25N9bd7VNVRubKDv3tjTfvkJwy6mpiKMBpuEe12Z5LgVroaaC4ZUnW
          tFOm+R1WQSZ+fd0TkECjn0CHVEv36griIDqduOIEdpcyVYFfP6u7XA+bDpfDFCcjCm6sDoj8/TvzxlObCg0AZVugt+Ws9DIgdklCUuXyeJ6y29t33oN1JbZF
          0N9OGgBh5I8ni0qnhmR5f4iU3CjZJ1ivlV7sYmghfS0QtUSd7Jtxq8NJviwIBqpz1Xhm0FRuT7m3YFCE4ebrHKz6iChPORjJnjskZcfsB3ZhlGCCA2dxCuv9
          ujOh/GwWM0VObYoUx6vG2ywS1vhJLZS5tq9iQJWdlH6hSxiCosiLVnomz150RbUi69+xGykWpp6/kLWctkE8GmBE8N7GkmRZ94wI2x6zvBYgIextq3q6GMOj
          Bn5kSK+SDe0a5P7Q81sKHGnMaXDk+YOQvjdo78VJFdzIf1VttbVvYMowSM6g8RMBta1p+6JWz+7eYmdXs7Xx3xr4hv0BT+4PsAJ0b2ujtptv1/GOy7CEJRFg
          zuxyDwpqdye3DIs8TWPIfS+77N4mEUgx2ZVUyHDbr/b3e5dDB5z4/rA35IfP0ITvDl/xCzlf8JKRsvEirvWMfhY3dVbuymd3bcRNHX7EU7mpQ8nKXAX1TZ3I
          jyidyZs61tR2nGlzU8dzfCeYKfds/KXrkmV9z2bqeKYZKPdsiGcTZ9m+WcMQPF7hRbG+lYFwg91JEFefylcd/pzxIzgVxLjrEoxmXlThrjpvh1+7NzFwkL0+
          Ft2F+IUUCdGF5bkfbSGyA0a8ZcuhYaSeb9sEeM2RL0gaIP28NlmF8qaOkqT6iNNEkHXL6QdOW18i+HA9cjDn5+rdhE3q5RP1rgkLpLy6hPqGAH0wE2eb3q3d
          vwGL3zFu3VOYgwxXCCfii37BsimqCcOk2CVR8pBznPXZjXMdDAOsOgw4L1KDdrB/5aJBStycekoqsIu/5+IUn4xtWFzabVB2gZVhaslZ3StmkysKUu42GzwA
          +2o31T1o6IvYSQ8JV4ZXz2TV559EfDiQCk+bgPDirkuT65v1qLNHuBQyKJGAUlnrdBg6CsC8fZUskxQvxLJeyuEEqZumYucgxSuRTvKokCvKlK+Kpzp7tVf/
          vKFRQq6btfsmLP7m0Ln/g8mDw2pNPL7H+2qycMs34t3Gkuj8JoXj1pcOYlu5deCa7VsHjiP71fDsWXPYlhkut3dSltdHW0cylcrooV/PVQuVU28fSynCYlld
          +1Yqvf16J9sh69xBwo5HQUSIp1fAG72g0S6kkb7JhU3H15vDHw9KMR+rVX9INnhnmkCaQbJkQwY+HI9Xd7f86u/dLb/BjZdeH+4g/9PClJTl/YjdOBzxpiQC
          h8fDemi5hSZ+8ZsWsjdwDr6IbSXRxu7sjTQexDCHcj/KyF60VGR5P4pzvLXMPCs7rnU/+rHQSK5tQUwoQsddHDnfht1mzgBzaOSfHjL6nN+xK0wP3/z79z/9
          y/fwlb3JXrccp9bSlBCkh3R9XLvr/0eMCrL5Y916bnmyd3uJ3+XZKlnvCvLb//z2fxRRqJFs48Jv+XHA8vkcuOWuBLKVHXDfRwmM1CCuKGhJRg8/fdPA46y8
          5bx8uEPtZNDwYdTQHV6gF/4+3AHMmsEsv+D4MVRUsD+RPV3jEv8b2AkZd5hsCXL0FnpKwC2ekFLQWDxC+A4RL69hjNQR2AcrUmB1ZfvVHb/O/3A1hrBdK6si
          Cavx4goLBpX243d//unj/UFyYz6+A9sYa7jOmeboRqDZhqvbhqVZhq3js+HptuYYHjQE8N9sbxteqvOXqcY/8X6aGPZ+ptl27KZGABOwVuhuYyd802EADof/
          pp8sK+WPM51/YJ10MeS95WjO59Htw12YFGFKtfD5fmRZwI0X+IW5gTL3Iwc6jCflLoPFqP1s2Y/1cnEaudYPFqCzt9mPCb82RGQx/Jjsd6Nbno7LwzV7GwsW
          Zb23Zpo1+wAtM8AYF4AfdP7BYxhs8jxT6Amz4QTON1P4wf9YOANTMYo1jRa7q8a6fuYrYXfjYSYMPTVYiT/SYB2wDP7PRLAVcYMJrSas7pkTQVmeqXmx+wEx
          n8U2mxXNi8ptR4NOM1jmTAv2lkkshgigo8NTrHt7Pfhhtg9+cNUvusVRBGlX8HMZfkGDn9/gZzkcvx75nb3LyI4/4hco7Md+q+MU6BUbpvXB8sXTSFMvlUvu
          oyNp0R4JbXhkqk0F7vD0A8gtCNQeuNZ80Kb6NHbUd236uYUDkCiewV/LYciNJyzGUUg51Vz4CBPhn8+iy26t4jMFsB4uAn98bRrDgh3ia77ADp6AAAA6nrLx
          pIDYRJ3AQ8m03I3u6Z4G/8O/YuU0fFSxwZ6AkIuC6csu+6Ilm6DrnhZoAbA/kPiqtgAZ5O0tV4LlfbAM0F4U6wOrwt8uY/igJFvlZ/Vy1hUMy0JK2VowxG0u
          yxALqNzeIF0ZUXC4DcS0kKSftQ/AED+VlILYoIxV/OFjbE1B7PxPwNq9A4zxUxjqxZaZgqx7qEeWuQ8+WC77ZdPstipogOVqPvJPEBsSmKzTwdTYZ11wI81b
          ZNzgR4b4B2vKelpcBkoKKU5LY0FnZ6Cz+Edz9dnnjQuiaXlyWiYHb6B0sPdSR+MkLWN2kFwlKthGUAZ374dgTUB/LJP9+Qi0CFDi7U9+S1FAD1CvkRV6Q4s0
          J1FHspy9ZdeCjKL8AWbz90B2f697gsgD4yz/EyqAFH9tYBwWlR87q4AlgnX1De89WgU71X3mlLz3uEIrRR+FTe8d/Ogz7+N9Rl+ANglY4sZclMsqL2hbflCN
          HNCP1NZ8fAWdxvXz1BV1+8zbp9lnVC9vD0Lo7nUfhc22YCGxu+eLgWAXwpS47VO04JOzMQEp3cXlB3t3Y+qAIswVKFbMAtfCvtdtJmvDiY8yGMAA7z67fxjf
          QQ6mYUj7bQ5yw25Pu/D/IorhxyYhGCl2dPQw/tM1CyK+ZD//7W/syUAlv/nTGOLM/fqhDjVoGd6X9w8fIQDJ1tfl/X22S9N/Go/n5Q077Qnp4fXtl6/vHkbj
          n2/Xk/D+4fow/no8H39NNtvFeDK+w+e0wscHfFyzxxE+/rLL8WU0HsHLO2e2GB+/hD/f3EjYPF29P1xpmyTKWG5xwH8kaD5+D2kASCaKyZex+Bd4YFbx7+7A
          0+A/uTP+ecLKeTjGDQJiznAMLzLKMYE1sWx7MoMBUxhwnFxpeUhJJiH/GV/yBnZgRjNKcR5z6pjOsoZt2RPbCia2M+3BNk0/CAZgm4CpA+AtFXgRAudq6MUv
          u9/+N6LK4sMpmbIp3tnk/3v7tt5GriTNd/+KLAHrJEdpti51samiBLpKHmunqqSWyp4FNHpIkSkpbZJJZ5JyVUkFeJ4W+wP2ZbEDbGGAGXQD/eRZLNCPy3/i
          X7LxRcS5JZOSetCzD1Uik3nuceLE5Ys4m1vbmalsiwa9+fTLZOvJk6UOPNt4vJkOlzuATj99kmw+2/Z6QDIZrCXag6PFv5XRsIB9xfXh4mKQPktR3/ZXW483
          vrR9oLa3NrZ4Rut9+OrJk+2NjYY+PP4q+XI72fB6QFRQpiM7CfuVfPcm4dnj7PE5U8DGs+2traduQE+Tra0vk80vlylgc/vZ9uOmSfgq2dx8kjx7Znrwmd1q
          ItS9hhbb+zmfEGck/X82uOInrdhqtoEFmZNWtWOi6lFGVZD4n/VuPiaDi0v8gZ4TQ6yD8HvO39jUMXkfJxf5aJaVvZjUPzr4smr2WhzwVe/0jL8f4TAf9i7S
          UZXxA/sFISVvc5qnhJUP+QhEMpSngyHvYjMqVYR7j3RIyKv1Rsyr+oZmTRI9j/QODCztbiba025Msk5V5RVU8W7c548wreD4uxwzXPIkK6/zxb8WFb06HBJH
          rFBqQKreqLjEx6tiXvIzpAaAWkPUPlp8ehSdFPOoiFJbKeO+xotPM2J8NLfRjSqCHzvRi2JMullRVfT+D3Oa9z2aRJo9WBu78RtobtkERt8yy6P5OI2oHL2O
          VG/pkKappP9JVS/TCBMdTbPycj6ZpZ3oZX6ZU8uP5UeqkvRPGnxEL/40z6dZRH2kcc7ld1LlqL9RMRV9uEND/hnCpoyn73pMzcwWn5A9LcWeIhV88anMaVQ0
          SOQ1yzF3RSe6oV+IiRcfo5N5ioZABePoIh9QuZyGMFn86TobRZMi+nuSoav+dCo9Mf2jLlyltLgXF934+wLdnFc0hHE+uaKOmlmoIlK2MRnFBMYzGnffjM+f
          Z5phUq6p35jJfDKniqbZyGsaazWOfppnGF+O2fA6SV0B/QyJFrtKqzC8d5883kggK21u0F5FUEf3dCvZTh4nT5KnZ0y69OQsodUsfh4RKexPOMlXF+eZewoC
          4iCElxnke2KCGwkfI93YnCG0Gi7yJ5YtTZSILfvCNzJK7z7KttU9ciK7d8AbofufTw7fdKbIEdjijxUfkvnF+1awYdptGph0VgYMe/R0Zr9OilmOpYQJpI+B
          2F9GTPIZ9Ytz8NnnP2OmaRQHtDlp6O794pInaVbQ42OahpwmbUO+7sOhjm9qF+3GG53Nznb0f/8PrT9v8xJHSwrB4mI+kVx+A6q9Nc5mV8Uw6XQ6aXlZtek4
          zi9aj3RG2mU2m5eTaIl3nEqxs5Ypt8Pl5Gmv14urSTqtropZbKqozaE/5cuFib/J7MbtG//NjqxNz1sbtH66cdbeaW7npvhRiEjhTXTGlYs/XOdpNxp4hi3i
          HWNibzntBNklFb1OTzvxx/bOx3r3MkOfq0aHVmXRbLN9tJe9Q0vgLYYshIlEWBNaEmq3GDMbpM3eP/q7qD8ZlkU+5G7Ue5GP53C9rewDTOFoV16UQTJbA0+4
          LPlPmlfKpmqcJiXyAtFeF64PyY851B1dkJi3rZ1Pkk2reToyOqhsr6VOy+Y4ykegjGBlzbbpYbXqxUhdSstvc4j372vlsCvoxKyXyN7BeKxEdHvrfhCrcsMP
          /kY9Udtb8EIxzSZ/r3sz+IG+NxY4T5E74r39rc2ndYtEHCIwWnFZksbpD9aeZvGj27VSCe1UcK5s1BsWgzlopnNJZDnK8PHr9wfDVswvUmHiyiAFzTvaq/CA
          zZivaEI7dF63YqDl6U2eZkgTxXzWcqJFe8d97hHxmzda7d5uUFeZjYvrzFSXbH+5sYHdo9xjwpzjDU3zIOtxjR4vMv7HvuXerfaNEvZpPBLWHkPYoj/K1s9I
          qxmM5sOsapG85fmZ2nvhd3sQ7HjzSKddMbqutYg5hfev19Qfw2L4BexAqXSv1ULW2eJCxL+OPH5JXWUiKAqa1Um8V/+x68mbImhmVXtPhtjVEbe7aMvv9Xw6
          pGpcr7CqZTGqWuDcIs+t7H9ihtxrGjvtIEtKdLqDblFFUdKp1Yrr4I4vBlcFreNZ3AYYaT8dXLXYDd3bveG/HQ0A7cm363Q0x5zxcPQFGFmwHXyXL1XnyElC
          SYmcdCxxElRNpPWwTqv7gSWFNb/HtHt2b1Qb7Yk+ekoEjVJE5tLps1MzWWcJjbkiLbv+Co2LCZBruL11sgjvPXZcdZxLvDej48r9wKIJPds8C/fl8uCldakz
          m/VnxOnP5zN6hS0AkN4qvKbKvL7Nr+fABX379vWrnjzdg1WhFfM8Eo3F8b0z2eDsrs1jjcvE++NoXhXdKF5vWbKj7SB0vRe/ICG7iKHuDeb0ob3equ+qGMJL
          KkoIi7ekJ9APLEuztjBOO1QBscf7+h541u/p9ouiFF6E03iYcv+VMuwSn93eyqOOWel2B8rrerzEq/GatzXv3IAJQFSOnZsPytOTWe8hHXHUSpOCCi2pesAs
          884Ov+DR4QkrtXTUTUbvaeT2vc+IBxukBfFfD8fP3wDvIG5s5rX1Y/Y+yelw8KqnHhyVdIKWs/f88+w0P7tj4VoxYjROl/NLY/uatNE+XTHb3Is1HTTRhcLN
          YmpiNc/EYunpJGTnvXQF3Bhp3LqWLVb0b5ZY/KNH+GFHV3qH5GuSQ3zWTgfsPnDlr1Tcb9/1IzYl2o0THK43VJWRxG0D1OlsBK9hWI2t4a6C7rglCduN9ZB3
          Bq8LMzQQLE7CYjTsEbGd0g9nO+ZDj1/ZUT0B6gYxcQht7bZ9hQrSC6ZlQ/3C0nqrVly4tVhXAkAIrfkONSbF2/LHni+PHmE7LCt4wT5UM21L18/XH1gJ8tSV
          Ngbaqzxtw67tSklLvN1EmT4raUm/2IZCh4KXz5xerEi8nrV+9w/V+u/oC4naWWsj2WqTHDBtVb1daDRUhl5EjuUWPsyK75AQ9gXt5ZYnVJUZrPCiuVpSpY0I
          rAUI0ViKVEnYMctaUxYq0cPsPGG+uZbbW5Ju0nNsMbZjEcfRbyqN2weaSt49qKzc+/nn1OSjXnOjn3/+aBVFeLm2azm2g9zatGg0PJrYUjagXXZDnVU+AkTs
          JpBv3dTs2I9iOcMclQ004rTSpDYSWmrqw859ErlLBSMUnY3aN7UDCDESe/FJOiLFC5poRpoYDXt0hcOyD4uhASlgwFQGJ1RpgnfqYoXUFuDkqJoAcU9nPzYy
          3lT9xNYG2YEYDX7WGVQF5kWoOVfU2xRHn8rHqMuXWS+L1iykRlrzkHModYJyZh4V2lU1TJpR0m8L2iy+ZnFZfEu06eifG1u5CgrGoD1l5SKQBglGr4GasnL+
          zkfquFB9SFYCR2lh2RIRLhMoAL0YJutZSn+t6hLXQUYzeraOt9fjGjomXpdP+CFex0/r8S69S63Ab6MYmECFQdou6QYwz2Ic9pr28CqcKIxEGby3F+N/ogOS
          umI4i0QahIcIT55PvVanilgJmuUY2RYDZxKcGV7qJMzBeD6a5YA33tUhrmNt9znXAhspPfoiXqfqpE/8HD3gD/Bo2Wr34ueGGTC4xpWTCeWqMZ/60O8ePc2q
          Qct7pHOAp+b4Yj+ZaQJurefMiB7UmCgEa0sVPqwb3PLSfAsS8huedb4JIxmScJTz5DfPrsVOCiJu9/nVNhYVZdECfeNVlmr8ddaRMjmv8RF7Xrxbc6gnHL0r
          Ru6jqWxbIGU7DXuxHtpKe020xUk7dJTeBgNdSd3B5vKGzAXXdpcegbgdkQOE4mZ5xbQ44qfOS/t7uueF6HXTxzbzbaThKqxMNS+igNZamjM+kRECxugNZ2p7
          Lm8xYcpHXaSrzaDDm7uuDGNb5c4BlEPVOojQ6iEc9caTvOsMcpJe+8yxd3qqPizz54jxjvFZchobEB89PS+gG3j+IfxuxIREpj7B2cHuh4p/hluLHgKuQ3/e
          wvRa8g9GmsBv80spx9bT+OyMpaTW6SzJhSbO2vCPK6O9C3FIUweS1AmDZseSymwvliwchidGwU/LgRSGfpWqcqw44zc9vhXiOT1JbueOmQdmMZj61g2DwvBf
          Yqa6az4kOrld/ctOwi7+S3T6uvo3sWBC8+HjKQ2QZEzU3PZkdIMfvUOIqWFKaUSmkNdx2W5OBGQBvi4X2nIN9gydcRAATXmssogtIabGVYXa92h9kesNU2B7
          WKY/k8Y3a4X6O2anZbQh9lJBH+LkT1VHHLitkvTcjrqA2h0Sky5nV3Qe5xhjb5L9HJ1ks5bIumysvr09PWubwqPe7kiCt4Yi/PMD8HVSC/IPULO4aWIe71Up
          0aY+/1yrrHuRtIggUXtcci9mi3sRsUE/7gYV7cX9y3laDtnEojbn2Pfzij9xWMSmZmJX017AfIFAB9M5/SyKTo1GxppPEm9syu5FttPivMzgthRfIz1/A8Km
          GtV9HJG0OUFwo/GLsIeiA+Zi+MxZgjbEHX5761ZDJn53gxrcAosqM8jNke8ART/KPDPejyzK3pEUmluHizhKhkWJBpkupDGZrgZHnlkD47ugtreVVQ143so0
          mglPw9NxNsjYAzMfs3c1xYrMaefmH6hVNGq43tlnkeFyyMebTJLg3J8FHM+c+bNsuiZ3geltZZI3xouIQJDC3Zhs4ZAhkN3k8SWmiM7sxfjfEx/laWhSnLQd
          D/TrQqbftYeJI8pQbb3AR8rZusxT3Yn7WaSnqZ638cn+d9FR/+DN/qs48ehyj/31SWQFNfNDG1Y8In/noU+en5e7II9sHpX5bMwr9d3YBy1YV+IQCIUyui4G
          iz92opdS6Icsn1Gh9vpndMZrem4zIYj4qM03bjMQsylvXb5MwU538OawmK25mZId7+b9amv3hFqfZJeLXwd50cEwguKiEa7tAnZwXXzo2EOLStKCHFvgwOLP
          syyvktreHGTljLcRsBaKJKh4a2MzDYTdZh2Ro1R+4tWssR9mfzRAFgLa6/WfjwTN4GabVye/BjCBuVrcpt3Kkimti9CCTjK1+1lNMEY0TSgl4lH4hIh9Tecz
          6/jedis3ei/zgb/mTVY2GaQMvRimlYlYqBda2aaeG3c0ZOUnZcv/jkaYYd45FuaPOCxqtcsmW5pUl3F+jcmOiPfRSqa5F4Mqp+C7eVn4UJi4yz/RTBKJMU5m
          VqbnKWwfvKogy6WNIuG/a7tHB68O3x5Grw5f9F9ZQpbu8oF1b6e/wS4Vnk2sIFv8a1pKk0vT5MemhxNszkGVfhiwy30nFveSmEMlrnUx6BjGd5KNDUKpiCZp
          NJlf05OCJmJyLXChgV3zlDfbQb/jqWyr2wfS1jT/uhhmowKn4Rxq9IfFp2va06YP++wux9lcQ0XQo2E6NYdZMZ+V9vj2+6AzzQYJ8W+jw6iAaNQduEBRVbyw
          dCgVnejQX34c9iP6kS1byExZB0kMPRTS1yoPUKX0eJCN5kBt0SnHJ2koxRnZwUpyxoEQxyIKKjav59B5bftK0/SKAYSFF2CnnDhjwX3x/rtONzqZzYe0gv15
          WZQpLURQzke9UQELsTOF3+STlBfvPquJovDWdhf/CJMIw8vmsnzGfPJczKVqwTAFAj3e1kJSnI/ni18VP2BoX1MNH/ChP+Llkgbo+yHRBL14ZmzX8XMNSxbN
          v6MV0+xWe86baTUoZkRSon6iy8uWuHT2jspiSEJTFYqNtALaX0UdQuKSTZVZUE3BsDW7YExw+stFVpJ01kEIwjyzK/WtYvYqIX89/zjmbzDKdeUY22iXPLuc
          T4bA5lUwICVMx19dRYv/VUWbX151HBXsQxFHp7HVqRWzdI4dElEImNJU7gklUcG3DdFQolnBvtGvaYvlIzuCkNlZw7PGBbrvu9aojC3GptxKQJgpcqzz9DRt
          ckwuTQggasoquOsqDegEY8qXt+wwpWUYOcs2+MAEe8LzkUSLP9CaFtd5tfiVFoC3dLhV+RRbsVGRkENTJVkL2JY514aZVQlU1Gk0ofTNGaX8i7hGyeXE7o4O
          8vnrs8HG4My6xJ39fDwf1eJI+8OcPc6ltOV4OKJ+AqnXrEKrrvrsuQesOZTsgo2fp8iVj3ATnRqkcsYBXToRq7i4cALmymlkoR3Scsne7rYR3R9uMkTbX6gX
          cM3UlQ/bdfOhine11tgs4/W60Zjod9/kkGaZx2aUNr6302TnHyZnv7Oq+NcC1HHuuKeikf/IwRee2KEVGavxj50Z0Umr7TSeBsUkmFUgWNfsXPLX5hc1x3RN
          6sfdhhGTKmtf+fomlQZYgqfHwCiyd7BH7sWvDZ6YHsxSmiyo4os/MLr5HYNGwMY9dS1cf6tRakrfVRHINSJH17+b6sN8eOdqn8zP8xKbjRThISltvM45jWGD
          VE297bdmcYvn03BTPKRPCEmTnfeQXmkccm07oo6G7Wj+173mU0BXLNrxIZ89pA5W5uioLAR9vOefVmCg5pfooiTNivkNDi6LaEddAWx+mF1nLDCmbL1QJiMW
          j7SssbKYiNVXyCyXqbGhoCJn7Mb9Z3XJZEmcJgWZWOWM5dcp5mWYeuJ0qBA6SdV1YNtIjeeLTxUdRGxhphNucMx8P4n5gjjTFzmTDgWm/8PiU4RJwTFS5Ik8
          zHzQfrRJk/mYzp0Ksj4sX5X0c86Hli+UXtFykNA+W/xx7NGoMWUZKG3n3vnQfTipQslvlYoRSppfFylukJ5AmEiZdKgSDAvzoBEVUH5D6eX3c7bpTbzICJpY
          PzKCypgIipXFpxky7IyVLKuqQCmNN/AKed4LPkANh/oephAOKohYj2+0QNjoA2VCyYrXICXc946b2/veNHEX97zGHhMifvMeEUjziyp52hdFMvgPEsPq4pAJ
          u7hHdfF9icaMsiIyhRb3G41dIXa0+BOJmYmymMiLU0GhebX442SQp2A9riPhjtBkjWsN1B6oNbsvc+iKY8PjvL2oernVavza0/eV6C4vqQ8ncCbRv9/rvxP+
          pybVoQpG4ZlBFRiNBXU5aDHOVxKRrAkuPFToXX1Cn9inJOdx3R9K/SrGtEsxq6ojsMOrpPGgk3NikfIhn/CHE6gP+Lv4dA7j+9lpfib21uHdNtCGZBV8RdAa
          m1zHmVl78C/SSrBiCNGhCrxfv8kGV6n+TPPv1d68y78jvlkQM64KZm9WsD/BEl6gMllB0p8MAyMd6TwrZ/OSlKT6MkvkET0kIZtqzKFNXWJmsk7kdLL8co74
          hSq/nLCZYIyQWGxqWA4qFKs8LGdRqSlS2ZsVjOoBWtC7fmZ/5P8vXeqQmazajh2fhWKIJ3Is2VkxsSJgzvW+s0mFlKYi2JbQVUhrJ4EGi8MtXGcfIgmMi7Y3
          ECoGlZpbs/FhrHLVrOkvDt98c/C33x3vR7Crcw6bg9f7b94ewhDAxm7HfsEMDkKL8SjF4lykH2jaz+lMc5atpQMUV7Pxhj71rSpqaYGHuFQ5wFpe+anlPolT
          3p3LOB8mVZPvhLat5aT5cMlMUdvz8qo+tICPfCjbs7rHRbFurlEIgMJ261lYjQQjXPcUz/06nV11LkZFUVo8xe+ebrTbnSnD/8pZ
